data=runif(1000,0,1)
bootstrap=function(data,n,t,n2,alpha)
{
  library(ggplot2)
  alpha=0.05
  data2=data.frame(data)
  n1=n2*n
  mean=matrix(nrow=500,ncol=1)
  varians=matrix(nrow=500,ncol=1)
  stdev=matrix(nrow=500,ncol=1)
  ba=matrix(nrow=500,ncol=1)
  bb=matrix(nrow=500,ncol=1)
  bbvar=matrix(nrow=500,ncol=1)
  bavar=matrix(nrow=500,ncol=1)
  z.alpha=qnorm(1-(alpha/2))
  for( i in 1:t){
    a=sample(x=1:n,size=n1,replace=TRUE)
    temp=data2[a,]
    mean[i]=mean(temp)
    varians[i]=var(temp)
    stdev[i]=sd(temp)
    bb[i]=mean[i]-(z.alpha*stdev[i]/(sqrt(n1)))
    ba[i]=mean[i]+(z.alpha*stdev[i]/(sqrt(n1)))
    bbvar[i]=(stdev[i]^2)/(1-(z.alpha*(sqrt(2/(n1-1)))))
    bavar[i]=(stdev[i]^2)/(1+(z.alpha*(sqrt(2/(n1-1)))))
  }
  b=data.frame(data)
  c=data.frame(temp)
  variansbaru=mean(varians)
  meanbaru=mean(mean)
  bbbaru=mean(bb)
  babaru=mean(ba)
  bbvarbaru=mean(bbvar)
  bavarbaru=mean(bavar)
  stdev1=mean(stdev)
  meanasli=mean(data)
  variansasli=var(data)
  stdevasli=sd(data)
  bbasli=meanasli-(z.alpha*sd(data)/(sqrt(n)))
  baasli=meanasli+(z.alpha*sd(data)/(sqrt(n)))
  bbvarasli=(stdevasli^2)/(1-(z.alpha*(sqrt(2/(n1-1)))))
  bavarasli=(stdevasli^2)/(1+(z.alpha*(sqrt(2/(n1-1)))))
  par(mfcol=c(2,2))
  g<-ggplot(c,aes(temp))+geom_histogram(col="black", fill="pink",bins=100)+labs(title="Histogram setelah Bootstrap")
  h<-ggplot(b,aes(data))+geom_histogram(col="black", fill="blue",bins=100)+labs(title="Histogram Sebelum Bootstrap")
  list(mean=meanbaru, varians=variansbaru,stdevbaru=stdev1, Batasatasmean=babaru, batasbawahmean=bbbaru,batasatasvarians=bavarbaru,batasbawahvarians=bbvarbaru,meandata=meanasli, 
       vardata=variansasli, stdevasli=stdevasli, bbmeanasli=bbasli,bameanasli=baasli,batasatasvarasli=bavarasli,batasbawahvarasli=bbvarasli,histogram1=g,histogram2=h)
}
bootstrap(data,1000,500,0.75,0.05)